title: Vatsal Suthar # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst 
  <br><br>
  Welcome to my portfolio! I am a dedicated and results-driven fresher in the field of data analytics, equipped with a Master's degree in Data Science & Analytics and recently certified by Google in Data Analytics. 
  <br><br>
  <a href="https://www.linkedin.com/in/vatsalsuthar/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-V761V4SF14 # your Google Analytics tracking ID here
